### ISSUE TITLE
Creating bucket is not triggering cloudwatch event.

### ISSUE THREAD

**Issue by rajangold02** [willh/henry#2]
Hello henry,

I have been seen your code and when creating bucket with acl is not triggering the cloudwatch event. Creating bucket with with acl is triggering getbucketacl event not triggering createbucket event.

Nice to meet with you on github.

Thanks & Regards,

**Comment by willh** [comment]
Are you creating the S3 bucket via API or via AWS web management console?

Which steps specifically are you taking to create the bucket? 

Which events do you see appearing in your CloudTrail log?

**Comment by rajangold02** [comment]
Hello,

I'm using aws console to creating bucket. But creating bucket working fine now. i tried to get event for putbucketpolicy but it is not triggering event. that is the problem.

Thanks,

**Comment by willh** [comment]
The CloudWatch Events that Henry currently processes are PutBucketAcl and CreateBucket, which cover API and Console based bucket creation and bucket permission editing. 

As this is a bucket-centric approach, it doesn't currently support inspecting IAM policy updates to check to determine if a user (or more importantly, the anonymous user) has been granted the ability to access an S3 bucket by setting policies and applying them to a user/role. 

I'll come back to this at some point when I've got more free time and investigate extending the tool in this way.

**Comment by rajangold02** [comment]
Sure. 

Thanks a lot for support Henry.
